apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: REPLACEME-eks-cluster
  region: us-west-2
  version: "1.16"
  tags: {
    cb-name: "foobar:cb",
    cb-chocolate: "pretzel:dark"
  }

status:
  endpoint: private

nodeGroups:
  - name: cloudbees-core-masters
    kubeletExtraConfig:
      clusterDNS: ["172.20.0.10","169.254.169.253","8.8.8.8","8.8.4.4"]
    instanceType: r5.xlarge
    minSize: 1
    maxSize: 3
    volumeSize: 50 # Range between 10 and 100
    volumeType: gp2
    volumeEncrypted: true
    volumeKmsKeyID: my_key_id
    privateNetworking: true
    labels: {
      partition: masters
    }
    taints: {
      partition: masters:NoSchedule
    }
    tags: {
      cb-name: "foobar:cb",
      cb-chocolate: "pretzel:dark"
    }
    iam:
      withAddonPolicies:
        autoScaler: true
        efs: true
    availabilityZones: ["us-west-2a"] 

  - name: cloudbees-core-regular
    kubeletExtraConfig:
      clusterDNS: ["172.20.0.10","169.254.169.253","8.8.8.8","8.8.4.4"]
    instanceType: m5.large
    minSize: 1
    maxSize: 3
    volumeSize: 50 # Range between 10 and 100
    volumeType: gp2
    volumeEncrypted: true
    volumeKmsKeyID: my_key_id
    privateNetworking: true
    labels: {
      partition: regular-agents
    }
    tags: {
      cb-name: "foobar:cb",
      cb-chocolate: "pretzel:dark"
    }
    iam:
      withAddonPolicies:
        autoScaler: true
    availabilityZones: ["us-west-2a"] 
vpc:
  id: "REPLACEME-vpcid"
  clusterEndpoints:
    publicAccess:  true
    privateAccess: false
  subnets:
    private:
#      us-east-2a:
#        id: "REPLACEME-2a"
      us-west-2b:
        id: "REPLACEME-2b"
      us-west-2c:
        id: "REPLACEME-2c"
